import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Inter} from 'next/font/google';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    keywords: 'Next.js, Typescript'
};

export default function RootLayout({children}:{children:React.ReactNode}){
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <main className="max-w-3xl mx-auto py-1">
        {children}
      </main>
      </body>
    </html>
  );
}
